#pragma once

#include <QtWidgets/QMainWindow>
#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QComboBox>
#include <QtCore/QRandomGenerator>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QFileDialog>
#include <QtWidgets/QCheckBox>
#include <QStandardItemModel>
#include <QListView>
#include <QProcess>
#include <QtWidgets/QLineEdit>
#include <QtCore/QPropertyAnimation>
#include <QtWidgets/QGraphicsOpacityEffect>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QMessageBox>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtGui/QPainter>
#include <QtWidgets/QStatusBar>
#include <QtGui/QAction>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QDialog>
#include <QtGui/QMouseEvent>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSpacerItem>
#include <qfileiconprovider.h>
#include <QtConcurrent/QtConcurrent>
#include <QtGui/QWindow>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QToolButton>
#include <QtGui/QScreen>
#include <QtWidgets/QWidget>
#include <QtWidgets/QGraphicsScene>
#include <QtWidgets/QGraphicsLayoutItem>
#include <QtWidgets/QGraphicsWidget>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGraphicsAnchorLayout>
#include <QtWidgets/QStyleFactory>
#include <QtWidgets/QAbstractItemView>
#include <QtWidgets/QSizeGrip>
#include <type_traits>
#include <qsortfilterproxymodel.h>
#include <Windows.h>
#include <Shlwapi.h>
#include "./RunAs/RunAs.h"
#include "QtComponents.h"
#include "./NTapi/NTapi.h"
